### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by alfasin** [datastax/SwiftieGPT#26]
I've installed and run according to the README instructions (on MacOS Sonoma 14.1.1 (23B81) with the chip: Apple M1 Pro).

and when I'm running `npm run dev` I'm getting:

Failed to compile
```
./node_modules/hast-util-to-jsx-runtime/lib/index.js
Attempted import error: 'style-to-object' does not contain a default export (imported as 'styleToObject').

Import trace for requested module:
./node_modules/hast-util-to-jsx-runtime/lib/index.js
./node_modules/hast-util-to-jsx-runtime/index.js
./node_modules/react-markdown/lib/index.js
./node_modules/react-markdown/index.js
./components/Bubble.tsx
./app/page.tsx
```

Is there an alternative to using the `Markdown` in Bubble.tsx?

**Comment by mfortman11** [comment]
@alfasin thanks for trying this out!

I was just able to spin up a clean version of this app without an issue

Can I ask what version of node you're using? I'm using the LTS (`20.11.1`)
Although it looks like `react-markdown` support 16+ something funny might be going on there.

If that doesn't work or if it's just easier to remove the markdown piece you can remove it like so

```
<div ref={ref  as RefObject<HTMLDivElement>} className={`block mt-4 md:mt-6 pb-[7px] clear-both ${isUser ? 'float-right' : 'float-left'}`}>
      <div className={`flex justify-end ${hasSource ? 'mb-4' : ''}`}>
        <div className={`talk-bubble${isUser ? ' user' : ''} p-2 md:p-4`}>
            {content?.content}
          <svg width="12" height="7" viewBox="0 0 12 7" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0.730278 0.921112C-3.49587 0.921112 12 0.921112 12 0.921112V5.67376C12 6.8181 9.9396 7.23093 9.31641 6.27116C6.83775 2.45382 3.72507 0.921112 0.730278 0.921112Z" />
          </svg>
        </div>
      </div>
    </div>
```
The only perk of the markdown for this app is that it nicely formats things like lists

**Comment by alfasin** [comment]
Thanks so much for your help!
My Node version is: v20.10.0

This workaround works great - thanks!!!
